# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shared/gate.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'shared/gate.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11shared/gate.proto\x12\x06shared\"]\n\x0bGateBodyReq\x12!\n\x04\x62ind\x18\x02 \x01(\x0b\x32\x13.shared.GateBindReq\x12+\n\theartbeat\x18\x03 \x01(\x0b\x32\x18.shared.GateHeartbeatReq\"]\n\x0bGateBodyRsp\x12!\n\x04\x62ind\x18\x02 \x01(\x0b\x32\x13.shared.GateBindRsp\x12+\n\theartbeat\x18\x03 \x01(\x0b\x32\x18.shared.GateHeartbeatRsp\"\xe6\x01\n\x0bGateBindReq\x12\x0b\n\x03uid\x18\x01 \x01(\x03\x12\r\n\x05token\x18\x02 \x01(\t\x12\x10\n\x08platform\x18\x03 \x01(\t\x12\x0c\n\x04lang\x18\x04 \x01(\t\x12\x12\n\nappVersion\x18\x05 \x01(\t\x12\x1a\n\x12support_voice_type\x18\x06 \x01(\x05\x12\x38\n\x0b\x63ustom_data\x18\x07 \x03(\x0b\x32#.shared.GateBindReq.CustomDataEntry\x1a\x31\n\x0f\x43ustomDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\" \n\x0bGateBindRsp\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\"\x12\n\x10GateHeartbeatReq\"%\n\x10GateHeartbeatRsp\x12\x11\n\ttimestamp\x18\x01 \x01(\x03*R\n\nGateOpType\x12\x17\n\x13GateOpTypeUndefined\x10\x00\x12\x12\n\x0eGateOpTypeBind\x10\x02\x12\x17\n\x13GateOpTypeHeartbeat\x10\x03\x42\x17Z\x15jinn_server/pb/sharedb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shared.gate_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\025jinn_server/pb/shared'
  _globals['_GATEBINDREQ_CUSTOMDATAENTRY']._loaded_options = None
  _globals['_GATEBINDREQ_CUSTOMDATAENTRY']._serialized_options = b'8\001'
  _globals['_GATEOPTYPE']._serialized_start=545
  _globals['_GATEOPTYPE']._serialized_end=627
  _globals['_GATEBODYREQ']._serialized_start=29
  _globals['_GATEBODYREQ']._serialized_end=122
  _globals['_GATEBODYRSP']._serialized_start=124
  _globals['_GATEBODYRSP']._serialized_end=217
  _globals['_GATEBINDREQ']._serialized_start=220
  _globals['_GATEBINDREQ']._serialized_end=450
  _globals['_GATEBINDREQ_CUSTOMDATAENTRY']._serialized_start=401
  _globals['_GATEBINDREQ_CUSTOMDATAENTRY']._serialized_end=450
  _globals['_GATEBINDRSP']._serialized_start=452
  _globals['_GATEBINDRSP']._serialized_end=484
  _globals['_GATEHEARTBEATREQ']._serialized_start=486
  _globals['_GATEHEARTBEATREQ']._serialized_end=504
  _globals['_GATEHEARTBEATRSP']._serialized_start=506
  _globals['_GATEHEARTBEATRSP']._serialized_end=543
# @@protoc_insertion_point(module_scope)
