# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: client/hall_push.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'client/hall_push.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from shared import shared_pb2 as shared_dot_shared__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63lient/hall_push.proto\x12\x06\x63lient\x1a\x13shared/shared.proto\"c\n\x08HallPush\x12\"\n\x04type\x18\x01 \x01(\x0e\x32\x14.client.HallPushType\x12\x33\n\rwealth_change\x18\n \x01(\x0b\x32\x1c.client.HallPushWealthChange\"F\n\x14HallPushWealthChange\x12\x0c\n\x04\x63\x61sh\x18\x01 \x01(\x03\x12 \n\x05stash\x18\x02 \x01(\x0b\x32\x11.shared.StashInfo*G\n\x0cHallPushType\x12\x19\n\x15HallPushTypeUndefined\x10\x00\x12\x1c\n\x18HallPushTypeWealthChange\x10\nB\x17Z\x15jinn_server/pb/clientb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client.hall_push_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\025jinn_server/pb/client'
  _globals['_HALLPUSHTYPE']._serialized_start=228
  _globals['_HALLPUSHTYPE']._serialized_end=299
  _globals['_HALLPUSH']._serialized_start=55
  _globals['_HALLPUSH']._serialized_end=154
  _globals['_HALLPUSHWEALTHCHANGE']._serialized_start=156
  _globals['_HALLPUSHWEALTHCHANGE']._serialized_end=226
# @@protoc_insertion_point(module_scope)
