# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: client/login.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'client/login.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from shared import shared_pb2 as shared_dot_shared__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63lient/login.proto\x12\x06\x63lient\x1a\x13shared/shared.proto\"0\n\x07\x45rrorSc\x12%\n\nerror_code\x18\x01 \x01(\x0e\x32\x11.shared.ErrorCode*\x8d\x01\n\tLoginType\x12\x16\n\x12LoginTypeUndefined\x10\x00\x12\x12\n\x0eLoginTypeGuest\x10\x01\x12\x12\n\x0eLoginTypeApple\x10\x02\x12\x13\n\x0fLoginTypeGoogle\x10\x03\x12\x15\n\x11LoginTypeFacebook\x10\x04\x12\x14\n\x10LoginTypeTwitter\x10\x05\x42\x17Z\x15jinn_server/pb/clientb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client.login_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\025jinn_server/pb/client'
  _globals['_LOGINTYPE']._serialized_start=102
  _globals['_LOGINTYPE']._serialized_end=243
  _globals['_ERRORSC']._serialized_start=51
  _globals['_ERRORSC']._serialized_end=99
# @@protoc_insertion_point(module_scope)
