# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: client/room_push.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'client/room_push.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from client import room_share_pb2 as client_dot_room__share__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63lient/room_push.proto\x12\x06\x63lient\x1a\x17\x63lient/room_share.proto\"\xa9\x03\n\x08RoomPush\x12\"\n\x04type\x18\x01 \x01(\x0e\x32\x14.client.RoomPushType\x12-\n\nenter_team\x18\n \x01(\x0b\x32\x19.client.RoomPushEnterTeam\x12-\n\nleave_team\x18\x0b \x01(\x0b\x32\x19.client.RoomPushLeaveTeam\x12\x34\n\x0e\x66ull_team_info\x18\x0c \x01(\x0b\x32\x1c.client.RoomPushFullTeamInfo\x12@\n\x14member_status_change\x18\r \x01(\x0b\x32\".client.RoomPushMemberStatusChange\x12>\n\x13notify_match_result\x18\x14 \x01(\x0b\x32!.client.RoomPushNotifyMatchResult\x12\x34\n\x0e\x66ull_game_info\x18\x15 \x01(\x0b\x32\x1c.client.RoomPushFullGameInfo\x12-\n\ngame_start\x18\x16 \x01(\x0b\x32\x19.client.RoomPushGameStart\"O\n\x11RoomPushEnterTeam\x12\x11\n\tenter_uid\x18\x01 \x01(\x03\x12\'\n\tteam_info\x18\x02 \x01(\x0b\x32\x14.client.RoomTeamInfo\"O\n\x11RoomPushLeaveTeam\x12\x11\n\tleave_uid\x18\x01 \x01(\x03\x12\'\n\tteam_info\x18\x02 \x01(\x0b\x32\x14.client.RoomTeamInfo\"?\n\x14RoomPushFullTeamInfo\x12\'\n\tteam_info\x18\x01 \x01(\x0b\x32\x14.client.RoomTeamInfo\"=\n\x19RoomPushNotifyMatchResult\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07game_id\x18\x02 \x01(\x03\"?\n\x14RoomPushFullGameInfo\x12\'\n\tgame_info\x18\x01 \x01(\x0b\x32\x14.client.RoomGameInfo\"<\n\x11RoomPushGameStart\x12\'\n\tgame_info\x18\x01 \x01(\x0b\x32\x14.client.RoomGameInfo\"9\n\x1aRoomPushMemberStatusChange\x12\x0b\n\x03uid\x18\x01 \x01(\x03\x12\x0e\n\x06status\x18\x02 \x01(\x05*\xfd\x01\n\x0cRoomPushType\x12\x19\n\x15RoomPushTypeUndefined\x10\x00\x12\x19\n\x15RoomPushTypeEnterTeam\x10\n\x12\x19\n\x15RoomPushTypeLeaveTeam\x10\x0b\x12\x1c\n\x18RoomPushTypeFullTeamInfo\x10\x0c\x12\"\n\x1eRoomPushTypeMemberStatusChange\x10\r\x12!\n\x1dRoomPushTypeNotifyMatchResult\x10\x14\x12\x1c\n\x18RoomPushTypeFullGameInfo\x10\x15\x12\x19\n\x15RoomPushTypeGameStart\x10\x16\x42\x17Z\x15jinn_server/pb/clientb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client.room_push_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\025jinn_server/pb/client'
  _globals['_ROOMPUSHTYPE']._serialized_start=964
  _globals['_ROOMPUSHTYPE']._serialized_end=1217
  _globals['_ROOMPUSH']._serialized_start=60
  _globals['_ROOMPUSH']._serialized_end=485
  _globals['_ROOMPUSHENTERTEAM']._serialized_start=487
  _globals['_ROOMPUSHENTERTEAM']._serialized_end=566
  _globals['_ROOMPUSHLEAVETEAM']._serialized_start=568
  _globals['_ROOMPUSHLEAVETEAM']._serialized_end=647
  _globals['_ROOMPUSHFULLTEAMINFO']._serialized_start=649
  _globals['_ROOMPUSHFULLTEAMINFO']._serialized_end=712
  _globals['_ROOMPUSHNOTIFYMATCHRESULT']._serialized_start=714
  _globals['_ROOMPUSHNOTIFYMATCHRESULT']._serialized_end=775
  _globals['_ROOMPUSHFULLGAMEINFO']._serialized_start=777
  _globals['_ROOMPUSHFULLGAMEINFO']._serialized_end=840
  _globals['_ROOMPUSHGAMESTART']._serialized_start=842
  _globals['_ROOMPUSHGAMESTART']._serialized_end=902
  _globals['_ROOMPUSHMEMBERSTATUSCHANGE']._serialized_start=904
  _globals['_ROOMPUSHMEMBERSTATUSCHANGE']._serialized_end=961
# @@protoc_insertion_point(module_scope)
