# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: client/room_share.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'client/room_share.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from shared import shared_pb2 as shared_dot_shared__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63lient/room_share.proto\x12\x06\x63lient\x1a\x13shared/shared.proto\"\x83\x02\n\x0cRoomTeamInfo\x12\x0f\n\x07team_id\x18\x01 \x01(\x03\x12\x11\n\tgame_mode\x18\x02 \x01(\x05\x12\'\n\x05seats\x18\x03 \x03(\x0b\x32\x18.client.RoomTeamSeatInfo\x12+\n\x07players\x18\x04 \x03(\x0b\x32\x1a.client.RoomTeamPlayerInfo\x12\x1b\n\x13\x63reate_timestamp_ms\x18\x05 \x01(\x03\x12\x11\n\towner_uid\x18\x06 \x01(\x03\x12\x0e\n\x06status\x18\x07 \x01(\x05\x12\x39\n\x15prepare_for_game_info\x18\x08 \x01(\x0b\x32\x1a.client.PrepareForGameInfo\"0\n\x10RoomTeamSeatInfo\x12\x0f\n\x07seat_id\x18\x01 \x01(\x05\x12\x0b\n\x03uid\x18\x02 \x01(\x03\"T\n\x12RoomTeamPlayerInfo\x12\x0b\n\x03uid\x18\x01 \x01(\x03\x12\x10\n\x08nickname\x18\x02 \x01(\t\x12\x0f\n\x07game_id\x18\x03 \x01(\x03\x12\x0e\n\x06status\x18\x04 \x01(\x05\"\xbe\x01\n\x0cRoomGameInfo\x12\x0f\n\x07game_id\x18\x01 \x01(\x03\x12\x11\n\tgame_mode\x18\x02 \x01(\x05\x12\'\n\x07players\x18\x03 \x03(\x0b\x32\x16.shared.SimpleUserInfo\x12\x1b\n\x13\x63reate_timestamp_ms\x18\x04 \x01(\x03\x12\x17\n\x0frelated_team_id\x18\x05 \x01(\x03\x12\x14\n\x0cgame_address\x18\n \x01(\t\x12\x15\n\rgame_tcp_port\x18\x0b \x01(\x05\"8\n\x12PrepareForGameInfo\x12\x0e\n\x06map_id\x18\x01 \x01(\x05\x12\x12\n\ndifficulty\x18\x02 \x01(\x05*v\n\x14RoomTeamMemberStatus\x12\x1d\n\x19RoomTeamMemberStatus_Idle\x10\x00\x12\x1e\n\x1aRoomTeamMemberStatus_Ready\x10\x01\x12\x1f\n\x1bRoomTeamMemberStatus_InGame\x10\x02*\x8f\x01\n\x12RoomTeamStatusType\x12\x1f\n\x1bRoomTeamStatusTypeUndefined\x10\x00\x12\x1a\n\x16RoomTeamStatusTypeIdle\x10\x01\x12\x1e\n\x1aRoomTeamStatusTypeMatching\x10\x02\x12\x1c\n\x18RoomTeamStatusTypeGaming\x10\x03\x42\x17Z\x15jinn_server/pb/clientb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client.room_share_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\025jinn_server/pb/client'
  _globals['_ROOMTEAMMEMBERSTATUS']._serialized_start=705
  _globals['_ROOMTEAMMEMBERSTATUS']._serialized_end=823
  _globals['_ROOMTEAMSTATUSTYPE']._serialized_start=826
  _globals['_ROOMTEAMSTATUSTYPE']._serialized_end=969
  _globals['_ROOMTEAMINFO']._serialized_start=57
  _globals['_ROOMTEAMINFO']._serialized_end=316
  _globals['_ROOMTEAMSEATINFO']._serialized_start=318
  _globals['_ROOMTEAMSEATINFO']._serialized_end=366
  _globals['_ROOMTEAMPLAYERINFO']._serialized_start=368
  _globals['_ROOMTEAMPLAYERINFO']._serialized_end=452
  _globals['_ROOMGAMEINFO']._serialized_start=455
  _globals['_ROOMGAMEINFO']._serialized_end=645
  _globals['_PREPAREFORGAMEINFO']._serialized_start=647
  _globals['_PREPAREFORGAMEINFO']._serialized_end=703
# @@protoc_insertion_point(module_scope)
