# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: client/social_push.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'client/social_push.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from client import social_share_pb2 as client_dot_social__share__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x63lient/social_push.proto\x12\x06\x63lient\x1a\x19\x63lient/social_share.proto\"\xfc\x01\n\nSocialPush\x12$\n\x04type\x18\x01 \x01(\x0e\x32\x16.client.SocialPushType\x12)\n\x07new_msg\x18\n \x01(\x0b\x32\x18.client.SocialPushNewMsg\x12/\n\nrevoke_msg\x18\x0b \x01(\x0b\x32\x1b.client.SocialPushRevokeMsg\x12\x39\n\x0freaction_update\x18\x0c \x01(\x0b\x32 .client.SocialPushReactionUpdate\x12\x31\n\x0b\x63onv_update\x18\x0f \x01(\x0b\x32\x1c.client.SocialPushConvUpdate\"G\n\x10SocialPushNewMsg\x12 \n\x03msg\x18\x01 \x01(\x0b\x32\x13.client.ChatMessage\x12\x11\n\tconv_name\x18\x02 \x01(\t\"^\n\x13SocialPushRevokeMsg\x12\x0f\n\x07\x63onv_id\x18\x01 \x01(\t\x12\x0b\n\x03seq\x18\x02 \x01(\x03\x12\x13\n\x0brevoker_uid\x18\x03 \x01(\x03\x12\x14\n\x0crevoker_name\x18\x04 \x01(\t\"\x9f\x01\n\x18SocialPushReactionUpdate\x12\x0f\n\x07\x63onv_id\x18\x01 \x01(\t\x12\x0b\n\x03seq\x18\x02 \x01(\x03\x12\x13\n\x0breaction_id\x18\x03 \x01(\x05\x12\x14\n\x0coperator_uid\x18\x04 \x01(\x03\x12\x15\n\roperator_name\x18\x05 \x01(\t\x12\x0e\n\x06is_add\x18\x06 \x01(\x08\x12\x13\n\x0btotal_count\x18\x07 \x01(\x05\"_\n\x14SocialPushConvUpdate\x12\x32\n\x0c\x63onversation\x18\x01 \x01(\x0b\x32\x1c.client.ChatConversationInfo\x12\x13\n\x0bupdate_type\x18\x02 \x01(\x05*\xa4\x01\n\x0eSocialPushType\x12\x1b\n\x17SocialPushTypeUndefined\x10\x00\x12\x18\n\x14SocialPushTypeNewMsg\x10\n\x12\x1b\n\x17SocialPushTypeRevokeMsg\x10\x0b\x12 \n\x1cSocialPushTypeReactionUpdate\x10\x0c\x12\x1c\n\x18SocialPushTypeConvUpdate\x10\x0f\x42\x17Z\x15jinn_server/pb/clientb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client.social_push_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\025jinn_server/pb/client'
  _globals['_SOCIALPUSHTYPE']._serialized_start=747
  _globals['_SOCIALPUSHTYPE']._serialized_end=911
  _globals['_SOCIALPUSH']._serialized_start=64
  _globals['_SOCIALPUSH']._serialized_end=316
  _globals['_SOCIALPUSHNEWMSG']._serialized_start=318
  _globals['_SOCIALPUSHNEWMSG']._serialized_end=389
  _globals['_SOCIALPUSHREVOKEMSG']._serialized_start=391
  _globals['_SOCIALPUSHREVOKEMSG']._serialized_end=485
  _globals['_SOCIALPUSHREACTIONUPDATE']._serialized_start=488
  _globals['_SOCIALPUSHREACTIONUPDATE']._serialized_end=647
  _globals['_SOCIALPUSHCONVUPDATE']._serialized_start=649
  _globals['_SOCIALPUSHCONVUPDATE']._serialized_end=744
# @@protoc_insertion_point(module_scope)
